packages:
  - playground/*
  - packages/*
autoInstallPeers: true
ignoreWorkspaceRootCheck: true
catalogs:
  build:
    tsdown: ^0.15.12
    tsx: ^4.20.6
    typescript: ^5.9.3
    unplugin: ^2.3.10
    unplugin-utils: ^0.3.1
    vite: ^7.1.12
    vite-plugin-dts: ^4.5.4
  icons:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/hugeicons': ^1.2.17
    '@iconify/utils': ^3.0.2
  lint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
  plugins:
    vite-dev-rpc: ^1.1.0
  test:
    vitest: ^4.0.6
    '@vitest/coverage-v8': ^4.0.6
    '@vue/test-utils': ^2.4.6
    'happy-dom': ^20.0.10
    jsdom: ^27.1.0
  unocss:
    '@unocss/core': ^66.5.4
    '@unocss/preset-web-fonts': ^66.5.4
    '@unocss/preset-wind4': ^66.5.4
    unocss: ^66.5.4
  utils:
    '@types/node': ^24.10.0
    debug: ^4.4.3
    esno: ^4.8.0
    tinyglobby: ^0.2.15
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/core': ^14.0.0
    vue: ^3.5.22
    vue-tsc: ^3.1.3
  taze:
    taze: ^19.9.0
onlyBuiltDependencies:
  - core-js
  - esbuild
shamefullyHoist: true
strictPeerDependencies: false
